### ISSUE TITLE
Restructure sar-status repo to sar-status-personnel 

### ISSUE THREAD

**Issue by kengu** [DISCOOS/sar-status#16]
Current structure is making it hard to find which repos belongs to the sar-status project. All repos are prefixed with sar-*, which is much to inclusive, since several other projects already use this prefix, and more are expected to come. Two solutions are possible

1. **Namespacing** - change repo names to sar-status-api, sar-status-user, sar-status-admin
2. **Move all to one repo** - all three are merged into one with subdirs api, user and admin

**Comment by Anders55** [comment]
+1

**Comment by kengu** [comment]
**Decision**
Since @Anders55 is +1 for both alternatives, I've decided to go for alternative 2. 

**Reason**
Although it is best practice to isolate each components in it's own repo, this makes the sar-status service more complex to maintain, understand, document, track dependencies and issues using GitHub alone. New devs need the lowest possible threshold for on-bording the project. Moving all three repos into one impose the need for more on pulls (more commits are inbound) before push. The careful placement of each component in subdirs should only result in a higher pull frequency by each developer before push. The actual conflict rate should not increase however, which would be a more serious problem.

**Comment by kengu** [comment]
Alternative methods for merging repos, see https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by kengu** [comment]
After talking with @RobertSasak, our devops consultant, I've decided to go for alternative 1 instead. This solution still have the challenges described above, but is better aligned with the deploy strategy supported by our hosting solution at heroku.com.

**Comment by kengu** [comment]
Progress
- [x] Rename sar-status to sar-status-personnel
- [x] Moved files in sar-status-personnel/sar-user to repository root
